# Generated by Django 4.0.5 on 2022-09-29 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_alter_customuser_email_profilepicture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilepicture',
            old_name='my_id',
            new_name='my',
        ),
    ]
